from __future__ import annotations

"""
replot_bistability_oop.py

Replot an existing .npz result file generated by run_bistability.py or by the
previous bistability script, using the shared SimulationResults/ResultPlotter
objects.

Usage:
    python replot_bistability_oop.py Results/polariton_bistability_results.npz --show
"""

import argparse
from pathlib import Path
import matplotlib.pyplot as plt

from polariton_bistability_core import SimulationResults, ResultPlotter


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("input", nargs="?", default="Results/polariton_bistability_results.npz")
    p.add_argument("--outdir", default="Plots/Plots_bistability_oop")
    p.add_argument("--show", action="store_true")
    p.add_argument("--no-save", action="store_true")

    p.add_argument("--time-trace", action="store_true", default=True)
    p.add_argument("--quadratures", action="store_true", default=True)
    p.add_argument("--phase-space", action="store_true", default=True)
    p.add_argument("--spectra", action="store_true", default=False)
    p.add_argument("--balanced-psds", action="store_true", default=True)
    p.add_argument("--bistability", action="store_true", default=True)

    p.add_argument("--fmin-mhz", type=float, default=1e-3)
    p.add_argument("--fmax-mhz", type=float, default=2000.0)
    p.add_argument("--rbw-mhz", type=float, default=4.0)

    args = p.parse_args()

    results = SimulationResults.load_npz(args.input, build_missing=True)
    results.print_summary()

    plotter = ResultPlotter(results)
    outdir = Path(args.outdir)

    figures = []

    if args.time_trace:
        figures.append(("time_traces.png", plotter.time_traces()))

    if args.quadratures:
        figures.append(("quadratures_vs_time.png", plotter.quadratures_vs_time()))

    if args.phase_space:
        figures.append(("phase_space.png", plotter.phase_space()))

    if args.spectra:
        figures.append((
            "spectrum_measured.png",
            plotter.spectra(rbw_mhz=args.rbw_mhz, fmin_mhz=args.fmin_mhz, fmax_mhz=args.fmax_mhz),
        ))

    if args.balanced_psds:
        fig = plotter.balanced_psds(
            rbw_mhz=args.rbw_mhz,
            fmin_mhz=args.fmin_mhz,
            fmax_mhz=args.fmax_mhz,
        )
        if fig is not None:
            figures.append(("balanced_psds.png", fig))

    if args.bistability:
        fig = plotter.bistability()
        if fig is not None:
            figures.append(("bistability.png", fig))

    if not args.no_save:
        outdir.mkdir(parents=True, exist_ok=True)
        for name, fig in figures:
            plotter.save_figure(fig, outdir, name)
        print(f"\nSaved figures to {outdir}")

    if args.show:
        plt.show()
    else:
        plt.close("all")


if __name__ == "__main__":
    main()
